eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: PRODUCTSERVICE
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/product/**

        - id: ORDERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/order/**